contributionManagement(
    "noakhali-donate-btn",
    "noakhali-donate-amount",
    "noakhali-amount",
    "total-amount",
    "history-section",
    "noakhali-heading"
);
contributionManagement(
    "feni-donate-btn",
    "feni-donate-amount",
    "feni-amount",
    "total-amount",
    "history-section",
    "feni-heading"
);
contributionManagement(
    "protest-donate-btn",
    "protest-donate-amount",
    "protest-amount",
    "total-amount",
    "history-section",
    "quota-heading"
);
